//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Apereo .NET CAS Client Redis backed Proxy/Service Ticket Managers")]
[assembly: AssemblyDescription("Redis backed Proxy/Service Ticket Managers for the Apereo .NET CAS Client.")]
[assembly: AssemblyCompany("Apereo Foundation")]
[assembly: AssemblyProduct("Apereo .NET CAS Client Redis backed Proxy/Service Ticket Managers")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0-alpha.2+Branch.develop.Sha.6f93f4f5e80c8082cf151ff392a0c9cc4bdecaa7")]
[assembly: AssemblyCopyright("Copyright (c) 2007-2019 Apereo.  All rights reserved.")]

